
package frontend;

import backend.EmployeeRole;
import backend.Product;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class PurchaseProductWindow extends javax.swing.JFrame implements Node {

   private Navigation windowNavigation;
   private Node parent;
   EmployeeRole employee;
   
    public PurchaseProductWindow(Navigation windowNavigation , Node parent) {
        initComponents();
        this.parent=parent;
        this.windowNavigation=windowNavigation;
        this.setTitle("Purchase Product");
        employee = new EmployeeRole();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCustomerSSN = new javax.swing.JLabel();
        jLabelProductId = new javax.swing.JLabel();
        jLabelPurchaseDate = new javax.swing.JLabel();
        jTextFieldCustomerSSN = new javax.swing.JTextField();
        jDateChooserPurchaseDate = new com.toedter.calendar.JDateChooser();
        jTextFieldProductId = new javax.swing.JTextField();
        PurchaseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCustomerSSN.setBackground(new java.awt.Color(0, 255, 51));
        jLabelCustomerSSN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelCustomerSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerSSN.setText("CustomerSSN");
        jLabelCustomerSSN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelCustomerSSN.setOpaque(true);

        jLabelProductId.setBackground(new java.awt.Color(0, 255, 51));
        jLabelProductId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelProductId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductId.setText("ProductID");
        jLabelProductId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelProductId.setOpaque(true);

        jLabelPurchaseDate.setBackground(new java.awt.Color(0, 255, 51));
        jLabelPurchaseDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPurchaseDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPurchaseDate.setText("Purchase Date");
        jLabelPurchaseDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelPurchaseDate.setOpaque(true);

        jTextFieldCustomerSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerSSNActionPerformed(evt);
            }
        });

        jDateChooserPurchaseDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooserPurchaseDateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCustomerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCustomerSSN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProductId)
                            .addComponent(jDateChooserPurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCustomerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCustomerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserPurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PurchaseButton.setBackground(new java.awt.Color(51, 51, 51));
        PurchaseButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        PurchaseButton.setText("Purchase");
        PurchaseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        PurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(PurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCustomerSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerSSNActionPerformed

    private void PurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseButtonActionPerformed
        String CustomerSSN= jTextFieldCustomerSSN.getText();
        String ProductId=jTextFieldProductId.getText();
        Date PurchaseDate=jDateChooserPurchaseDate.getDate();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d-M-yyyy");
        //LocalDate date = LocalDate.parse((CharSequence) PurchaseDate, formatter);
        SimpleDateFormat date=new SimpleDateFormat("dd-M-yyyy");
        //date.format(PurchaseDate);
        
        // to find if product avaliable at all
        boolean productExists=false;
        
        if(CustomerSSN.isEmpty() || ProductId.isEmpty())
        {
            JPanel Empty = new JPanel();
            JOptionPane.showMessageDialog(Empty , "Some fields are empty ", "Alert!", JOptionPane.ERROR_MESSAGE);
        }
        else 
        { Product[] products=employee.getListOfProducts();
            for (Product product: products) {
                 if(product.getSearchKey().equals(ProductId))
                 {  productExists=true;
                        if(product.getQuantity()<=0)
                          {
                            JPanel soldout = new JPanel();
                            JOptionPane.showMessageDialog(soldout, "All items of the product with id " +ProductId +"is soldout!");
                             return;
                          }
                 }
             }
        }
        if(productExists)
        {
        employee.purchaseProduct(CustomerSSN, ProductId, LocalDate.parse(date.format(PurchaseDate), formatter));
        JOptionPane.showMessageDialog(null, "The customer with SSN "+CustomerSSN +" has successfully purchased the product with id " +ProductId);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Product " +ProductId + " Inavaliable");
        }   //validate CustomerSSN also??
        
        EmployeeRoleWindow EmployeeRoleWindow= new EmployeeRoleWindow(this.windowNavigation,this.parent);
        
        this.windowNavigation.setNavigation(EmployeeRoleWindow, this);
    }//GEN-LAST:event_PurchaseButtonActionPerformed

    private void jDateChooserPurchaseDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooserPurchaseDateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserPurchaseDateAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PurchaseProductWindow(null,null).setVisible(true);
            }
        });
    }

    @Override
    public Node getParentNode() {
        return this.parent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PurchaseButton;
    private com.toedter.calendar.JDateChooser jDateChooserPurchaseDate;
    private javax.swing.JLabel jLabelCustomerSSN;
    private javax.swing.JLabel jLabelProductId;
    private javax.swing.JLabel jLabelPurchaseDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCustomerSSN;
    private javax.swing.JTextField jTextFieldProductId;
    // End of variables declaration//GEN-END:variables
}
