package frontend;

import backend.EmployeeRole;
import backend.Product;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class PurchaseProductWindow extends javax.swing.JFrame implements Node {

   private Navigation windowNavigation;
   private Node parent;
   private EmployeeRole employee;
   
    public PurchaseProductWindow(Navigation windowNavigation , Node parent, EmployeeRole employee) {
        initComponents();
        this.parent = parent;
        this.windowNavigation = windowNavigation;
        this.setTitle("Purchase Product");
        this.employee = employee;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCustomerSSN = new javax.swing.JLabel();
        jLabelProductId = new javax.swing.JLabel();
        jLabelPurchaseDate = new javax.swing.JLabel();
        jTextFieldCustomerSSN = new javax.swing.JTextField();
        jTextFieldProductId = new javax.swing.JTextField();
        jDateChooserPurchaseDate = new com.toedter.calendar.JDateChooser();
        PurchaseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCustomerSSN.setBackground(new java.awt.Color(0, 255, 102));
        jLabelCustomerSSN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelCustomerSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerSSN.setText("CustomerSSN");
        jLabelCustomerSSN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelCustomerSSN.setOpaque(true);

        jLabelProductId.setBackground(new java.awt.Color(0, 255, 102));
        jLabelProductId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelProductId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductId.setText("ProductID");
        jLabelProductId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelProductId.setOpaque(true);

        jLabelPurchaseDate.setBackground(new java.awt.Color(0, 255, 102));
        jLabelPurchaseDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelPurchaseDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPurchaseDate.setText("Purchase Date");
        jLabelPurchaseDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelPurchaseDate.setOpaque(true);

        jTextFieldCustomerSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerSSNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProductId))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCustomerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCustomerSSN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserPurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCustomerSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCustomerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelProductId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPurchaseDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PurchaseButton.setBackground(new java.awt.Color(51, 51, 51));
        PurchaseButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        PurchaseButton.setText("Purchase");
        PurchaseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        PurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(PurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCustomerSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerSSNActionPerformed

    private void PurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseButtonActionPerformed
        String CustomerSSN= jTextFieldCustomerSSN.getText();
        String ProductId=jTextFieldProductId.getText();
        Date PurchaseDate=jDateChooserPurchaseDate.getDate();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d-M-yyyy");
        //LocalDate date = LocalDate.parse((CharSequence) PurchaseDate, formatter);
        SimpleDateFormat date=new SimpleDateFormat("dd-M-yyyy");
        
        // to find if product avaliable at all
        if(CustomerSSN.isEmpty() || ProductId.isEmpty())
        {
            JPanel Empty = new JPanel();
            JOptionPane.showMessageDialog(Empty , "Some fields are empty ", "Alert!", JOptionPane.ERROR_MESSAGE);
        }
        else 
        {  if(employee.purchaseProduct(CustomerSSN, ProductId, LocalDate.parse(date.format(PurchaseDate), formatter))){
                jTextFieldCustomerSSN.setText("");
                jTextFieldProductId.setText("");
                jDateChooserPurchaseDate.setDate(null);   
                JOptionPane.showMessageDialog(null, "The customer with SSN = "+ CustomerSSN +" has successfully purchased the product with id = " + ProductId);
                }
            else { 
            Product[] products=employee.getListOfProducts();
            for (Product product: products) {
                 if(product.getSearchKey().equals(ProductId))
                 {  
                        if(product.getQuantity()<=0)
                          {
                            JOptionPane.showMessageDialog(null, "All items of the product with id " +ProductId +" is soldout!");
                            return;
                          }
                 }
             }
          JOptionPane.showMessageDialog(null, "Invalid Puchase process","Failure!",JOptionPane.ERROR_MESSAGE);
            }
        }  
    }//GEN-LAST:event_PurchaseButtonActionPerformed

    private void jDateChooserPurchaseDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooserPurchaseDateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserPurchaseDateAncestorAdded

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        windowNavigation.setNavigation((JFrame)this.getParentNode(), this);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PurchaseProductWindow(null,null,null).setVisible(true);
            }
        });
    }

    @Override
    public Node getParentNode() {
        return this.parent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PurchaseButton;
    private com.toedter.calendar.JDateChooser jDateChooserPurchaseDate;
    private javax.swing.JLabel jLabelCustomerSSN;
    private javax.swing.JLabel jLabelProductId;
    private javax.swing.JLabel jLabelPurchaseDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCustomerSSN;
    private javax.swing.JTextField jTextFieldProductId;
    // End of variables declaration//GEN-END:variables
}
